#lang racket
;; Unit tests of the unparser, and a round trip: for every form in the
;; corpora, translating the unparser's output must give the same datum.
(require rackunit shrubbery/parse racket/runtime-path
         mystery-languages/sh/translate mystery-languages/sh/unparse)

(define (t str [family 'fields])
  (define in (open-input-string str))
  (port-count-lines! in)
  (for/list ([g (cdr (syntax->list (parse-all in #:source 'test)))])
    (define-values (kind datum expecteds e-group) (translate-top g family))
    datum))

(define-syntax-rule (ok datum str) (check-equal? (unparse 'datum) str (format "~s" 'datum)))

(ok (defvar x 3) "def x = 3")
(ok (deffun (f x y) (+ x y)) "fun f(x, y): x + y")
(ok (deffun (f x) x (+ x 1)) "fun f(x): x; x + 1")
(ok (+ 1 2 3) "1 + 2 + 3")
(ok (- (+ 1 2) 3) "1 + 2 - 3")
(ok (+ (+ 1 2) 3) "(1 + 2) + 3")
(ok (* (+ 1 2) 3) "(1 + 2) * 3")
(ok (+ 1 (* 2 3)) "1 + 2 * 3")
(ok (- x) "-x")
(ok (- (+ 1 2)) "-(1 + 2)")
(ok (* -1 x) "-1 * x")
(ok (not (= a b)) "!(a == b)")
(ok (not (not a)) "!(!a)")
(ok (- 5) "- 5")
(ok (- -2) "-(-2)")
(ok (if #t (if #f 1 2) 3) "if #true | (if #false | 1 | 2) | 3")
(ok (string=? (string=? "a" "a") "a") "(\"a\" == \"a\") == \"a\"")
(ok (procedure? f) "is_procedure(f)")
(ok (deffun (f) (let ([x 1]) x) 2) "fun f(): (let x = 1: x); 2")
(ok (or (and (not a) b) c) "!a && b || c")
(ok (and a (or b c)) "a && (b || c)")
(ok (< 1 2 3) "1 < 2 < 3")
(ok (<> a b) "a != b")
(ok (++ "a" "b") "\"a\" ++ \"b\"")
(ok (if c 1 2) "if c | 1 | 2")
(ok (+ (if c 1 2) 10) "(if c | 1 | 2) + 10")
(ok (begin 1 2) "block: 1; 2")
(ok (set! v 4) "v := 4")
(ok (oset o a 17) "o.a := 17")
(ok (oset o "a" 5) "o[\"a\"] := 5")
(ok (oset (oget o a) b 1) "o.a.b := 1")
(ok (object (a 43) (b "hello")) "{a: 43, b: \"hello\"}")
(ok (object) "{}")
(ok (object ((if #t k k) 1) ((++ "x" "y") 2) (3 4)) "{[k]: 1, \"x\" ++ \"y\": 2, 3: 4}")
(ok (oget o a) "o.a")
(ok (oget (oget o a) b) "o.a.b")
(ok (oget o (if #t k k)) "o[k]")
(ok (oget o (++ k "")) "o[k ++ \"\"]")
(ok (oget (f 1) a) "f(1).a")
(ok (f) "f()")
(ok (g (f 1) (+ 2 3)) "g(f(1), 2 + 3)")
(ok ((mk 1) 2) "mk(1)(2)")
(ok ((lambda (x) x) 3) "(fun (x): x)(3)")
(ok (lambda (x y) x) "fun (x, y): x")
(ok (let ([x 1]) (+ x 1)) "let x = 1: x + 1")
(ok empty "[]")
(ok (list 1 2) "[1, 2]")
(ok (map (lambda (y) (* y 2)) (list 1 2)) "map(fun (y): y * 2, [1, 2])")
(ok (string-ref s 1) "string_ref(s, 1)")
(ok #\b "Char\"b\"")
(ok #t "#true")

;; round trip over the corpora (private one too when present)
(define-runtime-path corpus "corpus")
(define-runtime-path private-corpus "../private/corpus")
(define (family-of rhm)
  (string->symbol (cadr (regexp-match #rx"sh-([a-z-]+)" (call-with-input-file rhm read-line)))))
(for* ([dir (filter directory-exists? (list corpus private-corpus))]
       [rhm (directory-list dir #:build? #t)]
       #:when (path-has-extension? rhm #".rhm"))
  (define family (family-of rhm))
  (define forms
    (call-with-input-file rhm
      (lambda (in)
        (read-line in) (port-count-lines! in)
        (for/list ([g (cdr (syntax->list (parse-all in #:source rhm)))])
          (define-values (kind datum expecteds e-group) (translate-top g family))
          datum))))
  (for ([d forms])
    (define text (unparse d))
    (check-equal? (t text family) (list d) (format "~a: ~a" rhm text))))
